#!/usr/bin/env php
<?php

die(); // todo

$var = new anovsiradj\CopasDisk();
$var->cli($argv);

/*
$test_parameter = array('a', 's', 'd');
$test_search = array('q', 'w', 'e', 'a');

print_r(array_uintersect($test_parameter, $test_search, 'strcmp'));
*/

/*
function echo_cli($var = null) { echo $var, PHP_EOL; }
$test_opts_regex = array(
	'-x' => true,
	'--foobar' => true,
	'-x/' => false,
	'--foobar/' => false
);
// Options are following getopt() allowed characters (azAZ09)
foreach ($test_opts_regex as $opt => $result) {
	$e = preg_match('/^(-[a-zA-Z0-9]|\-\-[a-zA-Z0-9]+)$/', $opt);
	var_dump($e, $a);
}
die();
*/
